[book]
authors = ["Futex Labs"]
language = "en"
src = "src"
title = "D_D Cloud Docs"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
